### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by LuomingXu** [Zooz/predator#149]
**Describe the bug**

![image](https://user-images.githubusercontent.com/24503603/58798101-57256280-8634-11e9-87d1-421e4be8f433.png)
![image](https://user-images.githubusercontent.com/24503603/58798127-63a9bb00-8634-11e9-8962-4b260a4955bb.png)
![image](https://user-images.githubusercontent.com/24503603/58798154-715f4080-8634-11e9-8917-92d81043eb16.png)
![image](https://user-images.githubusercontent.com/24503603/58798183-8c31b500-8634-11e9-8e48-0592fb45b443.png)

**To Reproduce**

when i click submit button want to test this api, and i saw this error.

**Expected behavior**

**Screenshots**

**Version:**
predator latest Docker release

**Additional context**

**Comment by enudler** [comment]
@LuomingXu how did you install it? docker?
can you send me the command you used?

**Comment by LuomingXu** [comment]
OS: windows 1809
cmd:  docker run -d -e JOB_PLATFORM=DOCKER -e INTERNAL_ADDRESS=http://192.168.0.4:80/v1 -p 80:80 --name predator zooz/predator

i tried install in Ubuntu, but i failed. 
:)

**Comment by enudler** [comment]
docker run -d -e JOB_PLATFORM=DOCKER -e INTERNAL_ADDRESS=http://$MACHINE_IP:80/v1 -p 80:80 --name predator -v /var/run/docker.sock:/var/run/docker.sock zooz/predator


you have to mount docker engine socket "-v /var/run/docker.sock:/var/run/docker.sock"
the idea is that predator using this socket inside it's docker to create other docker which are the load generators

**Comment by LuomingXu** [comment]
i want to use it in windows, so i replace "-v /var/run/docker.sock:/var/run/docker.sock" to "-v \\.\pipe\docker_engine:\\.\pipe\docker_engine". 
because [portanier](https://www.portainer.io/) user this to run on windows, so i tried, but this dont work, so i remove it.
predator can only run in Liunx?
SO, there is the question. 
i really dont know $MACHINE_IP. i tried my server public IP, docker internal ip, 127.0.0.1.
none of them work.

**Comment by enudler** [comment]
We never tried to run it on windows so i'm not sure about it, we did try Kubernetes, DC/OS, linux and mac.

The public ip should work.
But first you have to make this mount work.
I suggest running 'docker ps -a | grep predator'
making sure docker runner was started and then looking at the logs 

One more thing is to look at the logs of the Predator and see what is the problem (probably issue in windows talking with the docker engine)

**Comment by LuomingXu** [comment]
![image](https://user-images.githubusercontent.com/24503603/58799952-40353f00-8639-11e9-8e14-40317ba61068.png)
thanks a lot. solved.
and another question. 
how can i not use 80 port? 
there are three "80" in docker run cmd "http://$MACHINE_IP:80/v1 -p 80:80 ". 
which should i change?

**Comment by enudler** [comment]
the first one.
how did you solve it for windows? 
Can you send me the command so i can update docs?

**Comment by NivLipetz** [comment]
http://$MACHINE_IP:3000/v1 -p 3000:80 will let you run on port 3000 and not on port 80

**Comment by LuomingXu** [comment]
@enudler sry, i don't solve it on windows. i just can run it on my Ubuntu server... :)
(i will try some times on windows)
and i suggest you should add one basic user control in it. (this is very useful)
Finally, thanks a lot for your helpful solvation.

**Comment by LuomingXu** [comment]
en....
if you want to add windows support, i think this may be useful for you. 
my knowledge about Docker is poor, may not help you ... :)
[portainer installation guide](https://www.portainer.io/installation/)
![image](https://user-images.githubusercontent.com/24503603/58801642-ae7c0080-863d-11e9-96a0-d96daf817470.png)
