### ISSUE TITLE
Allow updating custom javascript on existing tests

### ISSUE THREAD

**Issue by jinglesthula** [Zooz/predator#153]
Would be very nice to support this in both the API and the UI.  If JS has any bugs or needs to be updated, it would be good not to have to delete and recreate the test to pick up the JS changes.

The API could perhaps have an optional flag.  A button in the UI could trigger the same functionality to fetch the JS resource and replace the cached version.

**Comment by enudler** [comment]
hi @jinglesthula 

It's definitely how it supposed to work.
At first stage we wanted to add support for custom javascript although i understand it's not the best experience.

we will try to get it for version 1.2.0.

Do you currently use custom javascript in your tests?

**Comment by jinglesthula** [comment]
I don't - just doing some initial looking at different load testing tools and saw the ability to customize with js as a nice feature. :)

**Comment by syncush** [comment]
How does Predator handle custom js at the moment?
Does it download the content of the file and saves it in the test config?

**Comment by enudler** [comment]
Hi @syncush 
Currently you can pass file url when you create a test, predator will download and  save it on the database with a specific id. From now on the test resource will have property called file_id.

If we want to implement what @jinglesthula suggested I recommend on the following 
1. Add api for create processor file
2 Add api for update processor file
3. Add api for get all processor file
4. Add api for delete processor file 
5. When creating or updating processor file it will be possible to send url or a raw JavaScript 
6. Add support for creating tests with file id (currently it’s not possible. We support only file url)


This will allows us one to many between tests and custom js processor file

On 2nd stage once APIs are ready we can add a page to the ui to mange processor file resources and allow tests select its processor file from a dropdown.

Optional: validate JavaScript on resource creation

**Comment by syncush** [comment]
I agree that this is the correct and robust way to support custom js processor files.

Why does Predator download the contents of the file once and saves it in the database?

What if Predator downloads the file for each job, isn't it a better way to handle custom js as for now?

**Comment by enudler** [comment]
We didn’t want to that since used sometimes provide download links with ttl
Not everybody has the option to put file on same server which will Always will have access to that processor file. We can maybe add toggle if “force” download file.

**Comment by syncush** [comment]
I see your point.

Then your suggestion is truly the correct way to handle processor files.
I'll take a look at the current implementation hopefully I can help with that.

**Comment by enudler** [comment]
I have opened a new project
https://github.com/Zooz/predator/projects/6

Currently, there are 14 issues in this project (around half of them are in the backend and half in the UI)
Everybody welcome to join the effort. 

The FIrst task we should do is to design the API (openapi3)

Then add CRUD API for the processor resource.

@NivLipetz @OrFrenkelZooz @jinglesthula @syncush @manorlh

**Comment by jinglesthula** [comment]
This is awesome.  I think Predator is what a lot of people need (high quality, FOSS testing tool).  It's great to see the solid effort on continuing to grow and improve the product.

**Comment by NivLipetz** [comment]
The progress of this feature can be tracked in the following project: https://github.com/Zooz/predator/projects/6
