### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [Zooz/predator#156]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/Zooz/predator/blob/master/package.json#L51

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same for `path`. https://github.com/Zooz/predator/blob/master/package.json#L60

**Comment by enudler** [comment]
hi @DanielRuf 
Thank you for noticing that
pipeline is running...

**Comment by enudler** [comment]
merged
