### ISSUE TITLE
Support insecure SMTP server configuration

### ISSUE THREAD

**Issue by syncush** [Zooz/predator#161]
**Is your feature request related to a problem? Please describe.**

My main goal is to send predator reports emails through outlook's SMTP server.

It would be nice if predator will support more mail configurations such as :
- secure
- ignoreTLS
- requireTLS
- tls.ciphers
- tls.rejectUnauthorized

**Describe the solution you'd like**
Support more environment variables regarding mail 
SMTP_SECURE_CONNECTIONS - boolean
SMTP_IGNORE_TLS - boolean
SMTP_REQUIRE_TLS - boolean
SMTP_TLS_CIPHERS - string, its value should match OpenSSL ciphers list
SMTP_TLS_REJECT_UNAUTHORIZED - boolean

**Describe alternatives you've considered**
I haven't found an alternative to my problem, Predator in my workplace runs in a closed network (and many certificates have expired), therefore we cannot use Gmail or any maintained email service.

**Comment by enudler** [comment]
Hi @syncush 
Predator is using nodemailer for sending emails
And seems that it supports the params you mentioned.
https://nodemailer.com/smtp/#tls-options

Multiple 👍 👍 👍 from me on that.

**Comment by syncush** [comment]
Hi @enudler,
sure nodemailer supports the params I have mentioned but how can I configure predator to use these parameters?

Correct me if I am wrong, but as for now, I cannot configure predator to use rejectUnauthorized: false etc etc'

**Comment by enudler** [comment]
Hi
You can add support for this.
Predator supports configuration from process.env or from the configuration endpoint:
https://zooz.github.io/predator/configuration.html
https://github.com/Zooz/predator/blob/master/src/configManager/helpers/configDataMap.js

**Comment by syncush** [comment]
Cool, I'll do it.

**Comment by NivLipetz** [comment]
Closed #170

**Comment by syncush** [comment]
Okay, it seems like my fix for the configManager tests was included in the PR.

7005be5e840f0d80cd8f1275185cf74707ecd958

Thank you once again Predator team!

**Comment by enudler** [comment]
Thank you Daniel 💪
