### ISSUE TITLE
Predator(Reports): don't see any reports after running the test

### ISSUE THREAD

**Issue by Nuoky** [Zooz/predator#167]
**Describe the bug**
don't see any reports after running the test

**To Reproduce**
1. Go to 'Tests'
2. Click on 'Create Test' and save
3. Go to 'jobs'
4. Click on 'Run Now'
5. Show 'Job created successfully: 9dc36076-b9e8-45e9-b3c6-068b89015723'
6. Go to 'Last Reports'

**Expected behavior**
Test report generated after testing

**Version:**
 - Predator: [1.1.5]（Docker）
 - Predator-runner [1.1.5]（Docker）
 - Database [sqlite]（Docker）

**Additional context**
Observe the predator-runner via `docker ps` and it quickly shuts down.

**Comment by enudler** [comment]
This is usually happens when the predator runner unable talk with the “main” predator 
Can you please share predator runner logs?

**Comment by Nuoky** [comment]
It looks like host doesn't exist
```
internal/url.js:221
  throw error;
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: http://:80/v1
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at getPredatorUrlWithApiVersion (/usr/app/config/jobConfig.js:5:29)
    at Object.<anonymous> (/usr/app/config/jobConfig.js:21:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by enudler** [comment]
Hi

I guess you used this command:

`docker run -d -e JOB_PLATFORM=DOCKER -e INTERNAL_ADDRESS=http://$MACHINE_IP:80/v1 -p 80:80 --name predator -v /var/run/docker.sock:/var/run/docker.sock zooz/predator
`

Looks like you didn't specify the MACHINE_IP which should be your internal ip address of the machine. Predator runners should be able to communicate with the 'main' Predator using this ip address.

btw if you are using mac you can type this cmd to get your ip:
`ifconfig en0 | grep 'inet ' | cut -d' ' -f2`

**Comment by Nuoky** [comment]
> Hi
> 
> I guess you used this command:
> 
> `docker run -d -e JOB_PLATFORM=DOCKER -e INTERNAL_ADDRESS=http://$MACHINE_IP:80/v1 -p 80:80 --name predator -v /var/run/docker.sock:/var/run/docker.sock zooz/predator `
> 
> Looks like you didn't specify the MACHINE_IP which should be your internal ip address of the machine. Predator runners should be able to communicate with the 'main' Predator using this ip address.
> 
> btw if you are using mac you can type this cmd to get your ip:
> `ifconfig en0 | grep 'inet ' | cut -d' ' -f2`

You are right, because MACHINE_IP is not set. Thank U!
