### ISSUE TITLE
Built-in function $dateNow() and $randomNumber() return values as a string

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#178]
**Describe the bug**
Built-in function $dateNow() and $randomNumber() return values as a string

**To Reproduce**
1. Use {{ $dateNow() }} of {{ $randomNumber() }} in your test with debug and see the value sent

**Expected behavior**
Get the actual dateTime value as a Number, not as a string

**Version:**
 - Predator: 1.1.6

**Comment by enudler** [comment]
Won't fix this as it's possible to easily achieve with processors

**Comment by ggopaks** [comment]
Can someone provide an example? While I imagine it is possible to modify the request in a process, I do not thing you can set a *variable* to be numeric type and use it from the body of a JSON POST request. If you want to use a variable in a JSON POST body, you still have to enclose it in quotes: `"{{ my_var }}"`

**Comment by Laksh47** [comment]
@ggopaks Even though you use "{{ my_var }}", if its generated to be an int in the processor function, the request body is populated with the integer value
