### ISSUE TITLE
Hosting Predator's docs website & configuring the link in Predator's UI

### ISSUE THREAD

**Issue by syncush** [Zooz/predator#179]
I would like to host Predator's docs site on my machine and configuring Predator's UI docs link.

Since I work in a closed network I cannot reach the site hardcoded in the following file

https://github.com/Zooz/predator/blob/master/ui/src/features/mainMenu.js

**Comment by enudler** [comment]
Regrading hosting docs, Shouldn’t be a problem since docs site is part of the src code (docs/devguide) and is built using MkDocs which produces static html. 

Regarding url from the ui, we will need to add env var for that.
