### ISSUE TITLE
Expose artillery accept insecure certs in predator ui

### ISSUE THREAD

**Issue by jordandlaman** [Zooz/predator#204]
**Is your feature request related to a problem? Please describe.**
When running predator containers within a corporate network tests will error out with UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Describe the solution you'd like**
I have tested by hopping off the network predator runs great (yay!).  Would be nice to expose somehow the functionality artillery gives you by running predator with the accept insecure certs (from the command line you pass -k).  Since we don't run it through the cli the ui might be the place to do that. 

**Describe alternatives you've considered**
At the very least an endpoint to hit to flip it.  I tried passing an env var to the docker container but because predator spawns more containers I don't think the process.env was being passed.

**Comment by enudler** [comment]
hi @jordandlaman 
You are right, Predator spawns the predator-runners.

We should be able to add this functionality by adding param to configDataMap and sending NODE_TLS_REJECT_UNAUTHORIZED=0 when it's set to true.
