### ISSUE TITLE
Test POST service which expects a file.

### ISSUE THREAD

**Issue by dpfernandez10** [Zooz/predator#208]
Hi, is there any way to try a post service that expects to receive a file?

Thanks in advance.

**Comment by NivLipetz** [comment]
Hi @dpfernandez10 , trying to understand better,  what is the API that you want to be testing? 

Do you want to test an endpoint using POST with the file content in the request body?

**Comment by dpfernandez10** [comment]
Yes, we have to do some tests in which all the requests are post with json body, but there is one of them that does not expect to receive a json if not a file, I have tried to send a binary body but predator asks me that the body is between { }, so I don't know if it is possible.

**Comment by NivLipetz** [comment]
Currently Predator does not support sending binary files. I opened up a feature request for it

**Comment by NivLipetz** [comment]
Currently Predator does not support sending binary files. I opened up a feature request for it, it's definitely a good enhancement for the API testing
