### ISSUE TITLE
UI: Button for deleting "Finished" tests

### ISSUE THREAD

**Issue by requiemofthesouls** [Zooz/predator#211]
**Problem**
Parameter _Parallelism_ in tests creates multiple containers for API attacking. After finishing tests the _Completed_ containers accumulating in system forming a little inconvenience. It will be cool if you implement a destroy button for this containers in Predator UI.

**What I suggest**
Add a **delete** button near the stop button in `Last Reports` submenu, in the row where described a test. This button should remove **all related** containers with its test.

![image](https://user-images.githubusercontent.com/32811996/66393667-96056380-e9ec-11e9-96ce-834f755f6658.png)

**Comment by enudler** [comment]
Hi @requiemofthesouls 
I think that we need to address this issue.

Although I'm not sure it will be the most friendly way to do it as sometimes there are many tests and deleting one by one can take time.

I'm suggesting two solutions when the JOB_PLATFORM is docker.
1. When predator starts the predator-runner container start it with --rm option which will delete the container after it's finished, the downside of this one that it won't be possible to access logs after the tests are finished.
2. Add to the predator a configurable scheduler which will search for all container older than (x) hours and delete all of them.

I would go with 2, what do you think?
@NivLipetz @requiemofthesouls

**Comment by NivLipetz** [comment]
i think 2 is preferable since the need to delete the finished containers is mostly used as a garbage cleaner and then it makes more sense to do a bulk deletion rather than a one-by-one deletion per job

**Comment by requiemofthesouls** [comment]
Hi all.

> In addition to option 2, we can also add a "Delete all" button to the UI which will not wait for the given ttl configured to the scheduler and will delete all the finished containers immediately.

**Comment by enudler** [comment]
ok sounds good to me
so bottom line what we need is this:

- [Common - Define API for delete all containers in docker, all jobs in k8s ]
- [Common - Implement TTL for containers using configuration handler]
- [Docker - Implement delete all for docker]
- [Docker - Implement scheduler to delete docker container after configured TTL]
- [Kubernetes - Implement delete all for kubernetes]
- [Kubernetes - Implement using k8s API for deleting job or scheduler  after configured TTL]
- [UI - Add button] - @manorlh

**Comment by NivLipetz** [comment]
The progress on this feature can be tracked in the project here: https://github.com/Zooz/predator/projects/7

any help is always appreciated :)

**Comment by enudler** [comment]
hi @requiemofthesouls 
Button + API is added now under setting menu in housekeeping area.
We will add also the scheduler in the upcoming week
