### ISSUE TITLE
Support sending payload files on tests

### ISSUE THREAD

**Issue by luizhenriqueandrade** [Zooz/predator#268]
**Is your feature request related to a problem? Please describe.**
It's a feature that artillery already has, it would be a great feature for predator because others competitors don't have anything similar to this.

**Describe the solution you'd like**
On UI - support drag-and-drop to add CSV files, to make it more user-friendly.
On API - passing an option with the file path.

**Describe alternatives you've considered**
For example, sending a CSV, with usernames and passwords, file before running a test, which populates an array that is used on the test.

**Additional context**
the artillery docs: https://artillery.io/docs/script-reference/#payload-files

**Comment by enudler** [comment]
hi @luizhenriqueandrade 
sounds like a good feature.

**Comment by enudler** [comment]
merged to master,
will be released in 1.4.0
