### ISSUE TITLE
Support for K8s Read-Only file systems

### ISSUE THREAD

**Issue by ashtttt** [Zooz/predator#269]
**Is your feature request related to a problem? Please describe.**
Our k8s environment is configured to run pods with read-only file systems. predator runner is failing when trying to copy processor java script code to runner container.

**Describe the solution you'd like**
We should be able to modify the job spec of runner to add and mount volume using a emptyDir so that you can copy the processor code to that path.

**Comment by enudler** [comment]
hi @ashtttt 
Thanks for submitting this
This should be modified in the predator-runner project and may involve artillery changes

**Comment by enudler** [comment]
@ashtttt 
we addressed this issue in predator-runner 1.3.0
you can use predator-runner:latest.

the processor file now downloaded into memory instead of to file
