### ISSUE TITLE
Make predator compatible with Functional Testing

### ISSUE THREAD

**Issue by giovannirco** [Zooz/predator#291]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Given a test with just some steps and a processor doing assertions I would like to schedule it to run once every given amount of time, similar on what we already have in place when setting jobs with cron syntax.

**Describe alternatives you've considered**
Maybe a way to set duration of the job to run only once or allow to use decimals on arrival rate so I can decrease it to make it fit only once in the duration of the test (not sure if this would work, didn't dig into the code to make this assumption)

**Additional context**
This would be useful for situations where we can benefit of the simple UI and dashboard when dealing with simple tests that only check if the API is working and if we are getting the expected data, since we can explore the processor to make some advanced assertions without much effort. This is only available on expensive closed source solutions and the bill can get very high if we want to test every minute as the number of API calls can get very high.

This has been discussed with @NivLipetz over slack on this [thread](https://predator-dev.slack.com/archives/CKNS0HJQJ/p1586963143008900)

**Comment by NivLipetz** [comment]
Hi @giovannirco 
Thanks for the feature request! We will design the solution and release it in Predator version `1.4.0` as soon as possible

**Comment by enudler** [comment]
hi @giovannirco 
This feature is merged to master.

The native assertion will be added in phase2,
For now, it's possible to do assertions with processors.

**Comment by giovannirco** [comment]
Hey folks thank you very much for taking this into consideration! I am going to deploy it again later this week and provide feedback on slack
