### ISSUE TITLE
Support for deleting test report

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#329]
Some test run fails on the start, some are not relevant for any future use because they duplicate/bad state/test setup was wrong

In order to keep clean reports we would like to introduce a way to delete test reports

**Describe the solution you'd like**
API for delete report
UI support for the delete report

**Comment by NivLipetz** [comment]
I'd like to add in a further iteration `delete multiple reports` both in the API and UI, if we multi-select or select all reports to delete then to send it in a batch rather than one by one

**Comment by semihural** [comment]
It would be a good feature we also need this
