### ISSUE TITLE
Export to CSV test reports

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#330]
**Is your feature request related to a problem? Please describe.**
I want to be able to export a test report into a csv file in order to share or keep a hard copied version of test comparison reports.

**Describe the solution you'd like**
An export to CSV button in the `compare reports` view.
![image](https://user-images.githubusercontent.com/31369413/86536417-10b5cd80-bef0-11ea-958c-de24b08ad71d.png)

This exported report should have statistics like: `Avg p50`,  `Avg p95`,  `Avg p99`, `Client errors`, `Server errors`, Start time + end time, notes

**Describe alternatives you've considered**
Manually inserted test latencies into a CSV in order to compare them easily.

**Comment by DarkAEther** [comment]
Greetings!

If this issue is open to be worked on, I'd love to have a go at it :)

**Comment by enudler** [comment]
@DarkAEther it's yours 👍 
@NivLipetz and I will be glad to guide you on this

Important parts:
1. Design the API for this endpoint. need to consider in this API multiple report id's
2. Predator runs distributed load tests and is doing aggregations. this API is responsible for returning it:
`http://predator.eks-mars-apps.zooz.co/v1/tests/<test_id>/reports/<report_id>/aggregate`
It produces a point for every 30 seconds. we would like to output this to the CSV so later on, we can regenerate the time graphs.

**Comment by DarkAEther** [comment]
Thank you! Will get to work on it :)
