### ISSUE TITLE
Empty database password is not working in the environment variables

### ISSUE THREAD

**Issue by paparaju** [Zooz/predator#339]
**Describe the bug**
Empty database password is not working in the environment variables
**To Reproduce**
1. Try to start the docker container with below command.
docker run -d -e JOB_PLATFORM=DOCKER -e INTERNAL_ADDRESS=http://192.168.1.103:80/v1 -e DATABASE_TYPE=MySQL -e DATABASE_NAME=predator -e DATABASE_ADDRESS="mysql:3306" -e DATABASE_USERNAME=root -e DATABASE_PASSWORD= -p 80:80 --name predator -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/predator:/usr/db zooz/predator

2. In the logs you can observe that required parameters are missing error and container will not start inspite of having all the parameters. i tried with empty string (""/'') as well but nothing works. I have created a new user in db and then tried with password and it worked.

**Expected behavior**
Container should not with empty db password too.

**Version:**
 - Predator: Latest docker image
 - Database - MySQL

**Additional context**

**Comment by enudler** [comment]
hi @paparaju 

Most of the systems do have password for the database. 
And in that case, I prefer to throw an error before the predator starts up to alert on that.
In specific cases in local env when you don't have a password, pleas pass some string to overcome this.

I'm closing this.
