### ISSUE TITLE
UI Settings configuration save problem

### ISSUE THREAD

**Issue by haosre** [Zooz/predator#364]
**Describe the bug**
# UI Settings Configure Save bug.
- Problem come from declare "_isNaN: Uncaught ReferenceError: _ is not defined" in ConfigurationForm/index.js

**To Reproduce**
1. Go to 'localhost/ui/settings'
2. Click on 'Minimum delayed time for report update'
3. Scroll down to 'Save'
4. See error in debug console

**Expected behavior**
'Configuration updated successfully' appeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/8998768/92106516-b3b29700-ee0e-11ea-8385-7da2807ad72f.png)

**Version:**
 - Predator: 1.4.0

**Additional context**
- We can fix by add: './ui/src/features/components/ConfigurationForm/index.js'
`const _ = require('lodash')`

**Comment by enudler** [comment]
Thanks @haosre 
can you pull request plesae?

**Comment by enudler** [comment]
@manorlh fixed it and pushed to master
thanks for this bug @haosre
