### ISSUE TITLE
Consider using a k8s ConfigMap for the /v1/config REST endpoint

### ISSUE THREAD

**Issue by jlewis42lines** [Zooz/predator#385]
**Is your feature request related to a problem? Please describe.**
A lot of predator's most important configuration options are set via the GUI or the `/v1/config` REST endpoint. When predator is deployed to kubernetes via terraform, this is not an ideal solution.

**Describe the solution you'd like**
When running in Kubernetes, consider deriving the entire `/v1/config` data structure from a [Kubernetes ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/). This will allow those using terraform, to manage the entire predator configuration inside terraform.

Specifically, I need to set a nodeSelector and tolerations for the predator-runner. I found issue https://github.com/Zooz/predator/issues/298 which explained how to do this manually, so I'm no longer stuck (which is great!). Now I'd like to get this config into terraform, and I think having a k8s ConfigMap might be the answer.

**Describe alternatives you've considered**
The alternative right now is hitting the /v1/config REST endpoint manually. This is okay for small deployments, but is not a great long term solution for us.

**Comment by enudler** [comment]
Added in helm chart 1.5 for predator 1.5
https://hub.helm.sh/charts/zooz/predator
