### ISSUE TITLE
Add a Discord webhook integration

### ISSUE THREAD

**Issue by syncush** [Zooz/predator#404]
**Is your feature request related to a problem? Please describe.**
Currently, (`v1.5.0`) predator is supporting `slack` and `json` webhook format. Today, many OSS and organization are using discord as a communication tool,  a good addition would be to support discord webhooks.

**Describe the solution you'd like**
The infrastructure for webhooks is already set, just needs to add another `formatter`.

**Describe alternatives you've considered**

**Additional context**
Make it pretty :) Discord is feature-rich!

**Comment by xPolar** [comment]
Hey, I'd like to take this. Could you give me some more details about what you'd be interested in?

**Comment by syncush** [comment]
Hey so I was thinking we would use the same message as slack.

[doc of discord webhook](https://discord.com/developers/docs/resources/webhook)

@NivLipetz  @enudler what do you think?

**Comment by enudler** [comment]
sounds good @syncush 
files is definitely an option but not a must IMO

@xPolar like @syncush said you can take a look at the project and try set webhooks to slack/JSON
The code you are looking for is in: `/src/webhooks/models/webhooksFormatter.js`

We would like to allow users to set webhooks in discord format

**Comment by xPolar** [comment]
When I first clicked on this repository on the explore page, I thought it was in Python, just realized it was in JavaScript; sorry for taking up your time!

**Comment by enudler** [comment]
np @xPolar

**Comment by melkyy** [comment]
I'd like to participate in this issue

**Comment by enudler** [comment]
Hi @melkyy 
You can go ahead, if you have any questions please don't hesitate to reach us

**Comment by syncush** [comment]
Hey @melkyy,
Welcome to Predator!
if you have any questions, you can reach us at our slack workspace or just ask here :)

🚀 Happy hacking!
