### ISSUE TITLE
Add scripts for easily run and debug predator on developer machine

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#416]
To allow developers easy onboard on this project we want to include simple scripts for setting the environment

TODO:
- [x] Mac (@enudler)
- [x] Unix (@syncush)
- [x] Windows (Open for contribution) 

The script should run install npm install for backend and frontend
and generate .env file with required fields to run Predator in minimal mode with sqlite.

The script should extract the IP address of the machine so runners which run as docker will be able to connect to the Predator. (https://zooz.github.io/predator/installation.html#docker)

**Comment by syncush** [comment]
Ok so I tested it on a `WSL2` and unfortunately, it **does not work**, I get an ECONNREFUSED, I guess it because WSL2 runs over windows.
I lack the knowledge to debug it, if you got any ideas I would love to test them.

Setup:
Windows - 19041.508
Docker - v19.03.12

What did I do?
Basically brute force every relevant IP I found with `ipconfig` in windows or `ifconfig` inside my WSL2 shell.


Will report about Unix asap.

**Comment by NivLipetz** [comment]
@syncush have you tried starting predator as nodejs process and not dockerized on windows?

**Comment by syncush** [comment]
predator runs a process, I would like the runner to be containerized

**Comment by rohan2734** [comment]
hey i would like to work on this issue, what are the skills do we need to know? and how can we do it, a simple approach might be a good one for a good start.

**Comment by enudler** [comment]
Hi @rohan2734 welcome to Predator.

We need some help to create a script to run Predator in local machine with Windows
I already created today a branch with a script for Mac:
https://github.com/Zooz/predator/blob/chore/localmacsetup/setupLocalEnv.sh
Just need adjust it to run in Windows machine
the branch name is: `chore/localmacsetup`

You can find us in slack and ask any question:
https://join.slack.com/t/predator-dev/shared_invite/enQtNjgwMzE2NjM3MDcyLTg5YTIwMGQyNjZlMjQ4MDNjOTk5YTkwMWYwNzJkOWFmM2QwOGY0ODc3MDU3MWRkYTAwMjRhMjBhOTM1MzFmMjU

**Comment by enudler** [comment]
Predator developer mode now runs successfully in Windows/Linux/Mac
Closing the issue.
