### ISSUE TITLE
Change gzip toggle to be true by default

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#421]
**Is your feature request related to a problem? Please describe.**
Currently, if gzip toggle is not set to true (it's default false) Predator won't be able to capture args from responses if they returned in gzip mode.

**Describe the solution you'd like**
Change the toggle to true by default
![Screen Shot 2020-09-26 at 19 47 32](https://user-images.githubusercontent.com/11491327/94345792-1fb0a580-0031-11eb-9813-835603ea4f9e.png)

**Comment by ShubhamSood1406** [comment]
gzip should be set to True by default? I can do this, please assign to me.

**Comment by enudler** [comment]
Assigned, thanks @ShubhamSood1406

**Comment by hitmanet** [comment]
I can do this! Please, assign to me

**Comment by enudler** [comment]
@hitmanet assigned

**Comment by ShubhamSood1406** [comment]
> @hitmanet assigned

But @enudler, I made a PR to it.

**Comment by enudler** [comment]
@ShubhamSood1406 I'm sorry, have you finished it? I didn't see it :|
@hitmanet sorry, i have to unassign you but you still can take #420 or take look at our UI and improve it

**Comment by enudler** [comment]
@hitmanet you can take this if you still want to
let me know so I can assign it

**Comment by Abdirizak-Mohamed** [comment]
I have cloned and made changes can you assign if this is still available.

**Comment by enudler** [comment]
@Abdirizak-Mohamed it's yours

**Comment by enudler** [comment]
Hi @Abdirizak-Mohamed 
how is going with the issue, do you need any help?

**Comment by enudler** [comment]
Hi @Abdirizak-Mohamed I'm going to unassign it and let someone else do it
