### ISSUE TITLE
UI: In test edit mode, open requests in collapsed mode

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#431]
**Is your feature request related to a problem? Please describe.**
Currently, I open test, I need to collapse all requests to see the flow in a high level
**Describe the solution you'd like**
When the test opened in edit mode, collapse all requests 

Actual:
![Screen Shot 2020-09-27 at 14 19 55](https://user-images.githubusercontent.com/11491327/94363683-8df67600-00cc-11eb-9fd0-ac3919c0e200.png)

Wanted:
![Screen Shot 2020-09-27 at 14 20 04](https://user-images.githubusercontent.com/11491327/94363684-9058d000-00cc-11eb-8f08-d509e79864ab.png)

**Comment by mcastre** [comment]
@enudler Hi! Id like to work on this issue.

**Comment by enudler** [comment]
Great @mcastre 

We are available in our slack if you need any help :)

**Comment by enudler** [comment]
@mcastre hi, how is it going with the issue?
do you need any guidance there?

**Comment by mcastre** [comment]
@enudler Hey sorry! i'm working on it now. Had some stuff come up lately which kept me away from my computer.

**Comment by mcastre** [comment]
@enudler PR is ready for review. https://github.com/Zooz/predator/pull/456

**Comment by enudler** [comment]
Merged, thank you @mcastre
