### ISSUE TITLE
`sed` code in setup-local-env.sh does not work as intended

### ISSUE THREAD

**Issue by DarkAEther** [Zooz/predator#440]
**Describe the bug**
In the `setup-local-env.sh` script, the following lines delete lines when updating the `.env` file.

```
sed -i '' '/DATABASE_TYPE/d' .env
sed -i '' '/INTERNAL_ADDRESS/d' .env
sed -i '' '/JOB_PLATFORM/d' .env
```
These lines generate an error when executed:

```
sed: can't read /DATABASE_TYPE/d: No such file or directory
sed: can't read /INTERNAL_ADDRESS/d: No such file or directory
sed: can't read /JOB_PLATFORM/d: No such file or directory
```

**To Reproduce**
1. Clone the repository
2. Run the `setup-local-env.sh` script.

**Expected behavior**
The lines in the file are successfully deleted and the new lines added.

**Comment by DarkAEther** [comment]
If this issue can be worked on, I'd love to have a go at resolving it :)
Thank you!

**Comment by enudler** [comment]
hi @DarkAEther 
we are currently working to make this script cross-platform and better

can you please give feedback when you use this branch 
https://github.com/Zooz/predator/pull/438
branch name: chore/cross-platform-setup
and run the same script for feedback?

**Comment by DarkAEther** [comment]
Hey @enudler,

The chore/cross-platform-setup branch seems to work great :)

Thanks for the quick response!
