### ISSUE TITLE
Finding INTERNAL_ADDRESS does not work on all devices.

### ISSUE THREAD

**Issue by DarkAEther** [Zooz/predator#441]
**Describe the bug**
When running `setup-local-env.sh`, the following line obtains the machine's local IPv4 address.
`INTERNAL_ADDRESS=http://$(ifconfig en0 | grep 'inet ' | cut -d' ' -f2)/v1`

This may not generate the correct IP address for a machine that:

1. does not have `ifconfig` installed (Ubuntu 18.04 LTS and newer do not have ifconfig installed as far as I know)
2. does not have `en0` as the default network interface (devices with WiFi cards usually have interface names along the lines of `wlpXsX`

**To Reproduce**
1. Clone the repository
2. Run the `setup-local-env.sh` script on a machine without `en0` as an interface or a machine without `ifconfig` installed

**Expected behavior**
The IPv4 address should be picked up on a majority of devices.

**Sample Output**
```
DATABASE_TYPE=SQLITE
INTERNAL_ADDRESS=http:///v1
JOB_PLATFORM=DOCKER
```

**Comment by DarkAEther** [comment]
If this issue is okay to be worked on, I'd love to have a go at it :)

Thank you!

**Comment by enudler** [comment]
hi @DarkAEther 
we are currently working to make this script cross-platform and better

can you please give feedback when you use this branch 
https://github.com/Zooz/predator/pull/438
branch name: chore/cross-platform-setup
and run the same script for feedback?

**Comment by DarkAEther** [comment]
Hey @enudler,

The chore/cross-platform-setup branch seems to work great :)

Thanks for the quick response!
