### ISSUE TITLE
UI: Change buttons in "Run Test" form

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#449]
**Is your feature request related to a problem? Please describe.**
In the "Run Test" form, i'd like more pictures and less text

Current form:
![image](https://user-images.githubusercontent.com/31369413/95067466-8e19f580-070c-11eb-8afb-31644781a34b.png)

**Describe the solution you'd like**
- [ ] Delete "Cancel" since there is an "X" button on top right corner of the form that does the same thing.
- [ ] Change "Schedule" button to a "save" icon (see additional context)
- [ ] Change "Run/Schedule & Run" button to a "run" icon (see additional context)

Wanted form design (very rough draft):
![image](https://user-images.githubusercontent.com/31369413/95067954-3c259f80-070d-11eb-9c82-72653e6737b2.png)

**Additional context**
Please use following icons (we are open to suggestions for other icons so feel free)
Save icon: 
![icons8-save-80](https://user-images.githubusercontent.com/31369413/95067355-6460ce80-070c-11eb-981d-1c699e005300.png)

Run icon:
![icons8-circled-play-80](https://user-images.githubusercontent.com/31369413/95067357-6591fb80-070c-11eb-8b4b-08ca592a597d.png)

**Comment by rzhekova** [comment]
I can give this a go, if no-one else has picked it up

**Comment by hitmanet** [comment]
I can do it! Can you assign to me?

**Comment by enudler** [comment]
@rzhekova @hitmanet Hi :)

@rzhekova was first so I assign that to you
@hitmanet can you maybe take #421 #420 

We are available on slack if you have any questions

**Comment by enudler** [comment]
@rzhekova please use icons from https://fontawesome.com/

**Comment by rzhekova** [comment]
Hi @enudler, sure will do!
Are these two okay with you?

Save icon: https://fontawesome.com/icons/save?style=regular
Play/Run icon: https://fontawesome.com/icons/play-circle?style=regular

**Comment by enudler** [comment]
yes @rzhekova 
not so good with colors and UX so I leave that to you

**Comment by rebekris** [comment]
hi! I think I can do it!

**Comment by enudler** [comment]
hi @rebekris 
it's already assigned
maybe you can check #420 
otherwise, you can join our slack workspace and we can find something else nice to do in the ui

**Comment by rebekris** [comment]
Thanks @enudler, 
If you agree, let me make a preliminary design (img), so we can reach consensus.

**Comment by rebekris** [comment]
@enudler  ok, don't worry, thank :D

**Comment by rzhekova** [comment]
Hey @enudler, I just want to confirm something. Would you like the whole button replaced with an icon or do you just want the text within the button to be swapped with an icon? Thanks

**Comment by enudler** [comment]
hi @rzhekova 
whole button
