### ISSUE TITLE
UI: Create test form - add floating '+' button

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#450]
**Is your feature request related to a problem? Please describe.**
When creating a test, in order to add a scenario, before, CSV file, steps, and sleep there is a toolbar menu with each desired action. This isn't user friendly and does not look great:
![image](https://user-images.githubusercontent.com/31369413/95072383-c40ea800-0713-11eb-9755-1f617838dccd.png)

**Describe the solution you'd like**
Remove this toolbar list and create a floating button instead that would offer those choices in an upwards popup menu.
Proposed design:
![image](https://user-images.githubusercontent.com/31369413/95073229-25834680-0715-11eb-993a-a6e4dea46959.png)

When clicking the + button, a menu should appear above it with all of the possible options. 

**Additional context**
Please use following icons (we are open to suggestions for other icons so feel free)
![icons8-plus-math-80](https://user-images.githubusercontent.com/31369413/95073733-046f2580-0716-11eb-8174-d54d5620394e.png)

**Comment by cjdeleon62** [comment]
Hi I would like to work on this if possible?

**Comment by NivLipetz** [comment]
Hey @cjdeleon62 would be great! Assigning it to you
If you have any questions we’re available on our slack workspace

**Comment by NivLipetz** [comment]
@cjdeleon62 Hey, have you started working on this yet? We have another suggestion on how to solve this issue in a more cleaner way without a + floating button

**Comment by NivLipetz** [comment]
Hi @cjdeleon62 are you still intending to work on this issue? I'd like to change it and remove the floating button in the end and add a `+` button on different places in the screen, i'll rewrite the description. 
Just would like to let you know before you start working on it.

**Comment by NivLipetz** [comment]
Hi @cjdeleon62 i'm going to close this issue and create a new one with a different implementation approach, thanks anyways
