### ISSUE TITLE
UI: Alternate cell shading in tables to gray/white 

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#459]
**Is your feature request related to a problem? Please describe.**
Currently the tables all have white background without any shading. This is sometimes hard for the eyes to focus on a specific row when the table is filled with data.

**Describe the solution you'd like**
Alternate cell shading to white/gray/white/gray which will help us highlight different rows. When the cursor is hovering above a specific row, highlight it in a different shade of gray in order to mark it to the eyes of the user.

**Comment by JStruk** [comment]
I could take a look at this if you don't mind assigning it to me 😄

**Comment by NivLipetz** [comment]
Would be great! we're available on our Slack workspace if you need anything :)
