### ISSUE TITLE
Tests without  http:// or https:// fails to fire requests

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#461]
**Describe the bug**
When a step URL doesn't start with the protocol, the predator-runner will fail to send the request

**To Reproduce**
1. Open UI
2. Create a new test
3. In the URLs (base URL + step URL) (see screenshot) add address without https:// or http://
4. Run the test
5. The request won't be successful 

**Expected behavior**
Impossible to save test where the URL doesn't contain protocol,
The field should be in red with the correct comment
**Screenshots**
Current behavior:

![Screen Shot 2020-10-07 at 16 48 00](https://user-images.githubusercontent.com/11491327/95340063-66b65a80-08bd-11eb-8e30-7f824bb89a90.png)

**Version:**
 - Predator: 1.5.4

**Additional context**
A bonus to this issue is to add validation on the backend.

**Comment by tombrowndev** [comment]
@enudler I can work on this!

**Comment by enudler** [comment]
Hi @tombrowndev  that would be great! We are available on our [Slack workspace](https://join.slack.com/t/predator-dev/shared_invite/enQtNjgwMzE2NjM3MDcyLTg5YTIwMGQyNjZlMjQ4MDNjOTk5YTkwMWYwNzJkOWFmM2QwOGY0ODc3MDU3MWRkYTAwMjRhMjBhOTM1MzFmMjU) if you have any questions feel free!

**Comment by enudler** [comment]
hi @tombrowndev, Please LMK if you are still on this one, we will be glad to assist

**Comment by tombrowndev** [comment]
Hi @enudler 

Many apologies but I'm not going to be able to complete this

**Comment by anusha5695** [comment]
@enudler Can pick this too. Would you assign this to me?

**Comment by enudler** [comment]
Thanks, @anusha5695 
assigned

**Comment by anusha5695** [comment]
Thanks @enudler. Have also raised the other PR for corrupted test data

**Comment by anusha5695** [comment]
Hi @enudler, if protocol is not present both baseurl and url fields should be shown as error fields right?

**Comment by enudler** [comment]
Hi, yes

**Comment by anusha5695** [comment]
Thanks @enudler ! 
Have raised the PR :) Please have a look

One callout - this pr might have conflicts with the other PR cuz both are individual branches. let me know if one of them is merged, i ll fix the other one's conflict
