### ISSUE TITLE
UI: Allow edit scheduled job

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#462]
**Is your feature request related to a problem? Please describe.**
Currently, it's possible to create a scheduled test run
it will show up in the 'scheduled runs' page but it's impossible to edit it

**Describe the solution you'd like**
An edit button on the row which will open the 'run job' form (the same form that used to create the scheduled job)
The button of 'play/run' should not in this form and a cron expression is mandatory in this case.

**Comment by jakub1221** [comment]
Hi, could you assign me to this feature? i would like to work on it

**Comment by enudler** [comment]
Hi @jakub1221  of course that would be great! We are available on our [Slack workspace](https://join.slack.com/t/predator-dev/shared_invite/enQtNjgwMzE2NjM3MDcyLTg5YTIwMGQyNjZlMjQ4MDNjOTk5YTkwMWYwNzJkOWFmM2QwOGY0ODc3MDU3MWRkYTAwMjRhMjBhOTM1MzFmMjU) if you want to stop by say hello and if have any questions

**Comment by enudler** [comment]
hi @jakub1221, Please LMK if you are still on this one, we will be glad to assist

**Comment by jakub1221** [comment]
Hi, @enudler, regarding backend job update functionality, it lacks some of the fields like webhooks and notes, this task is specified as UI. Can i add missing functionality for the backend as well?

**Comment by enudler** [comment]
@jakub1221 hey, yes that would be great, although are you sure webhooks not supported?

**Comment by jakub1221** [comment]
@enudler sorry, i meant notes and emails
