### ISSUE TITLE
UI: Replace button to icons in 'create test' form

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#470]
**Is your feature request related to a problem? Please describe.**
In the "Create Test" form, i'd like more pictures and less text

Current form:
![Screen Shot 2020-10-07 at 23 09 06](https://user-images.githubusercontent.com/11491327/95382299-1b6a6f00-08f2-11eb-8a21-ada831cf8166.png)

**Describe the solution you'd like**
- [ ] Delete "Cancel" since there is an "X" button on top right corner of the form that does the same thing.
- [ ] Change "Save" button to a "save" [icon](https://fontawesome.com/icons/save?style=regular) 2x size
- [ ] Change "Save & Run" button to a "run" [icon](https://fontawesome.com/icons/play-circle?style=regular) 2x size

Wanted form design (very rough draft):
Use the same CSS and apply the same tooltip as was done by @rzhekova in pull request #455

**Comment by rzhekova** [comment]
Hi @enudler I can pick this up as well since I'm already familiar with that bit of code

**Comment by enudler** [comment]
hi @rzhekova, sounds great! assigned.

**Comment by rzhekova** [comment]
Cool, thanks!
