### ISSUE TITLE
UI: Add grafana_url param to settings page

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#479]
**Is your feature request related to a problem? Please describe.**
It's possible to configure the metrics plugin in the settings page but not grafana URL 
**Describe the solution you'd like**
Add Grafana URL input under metrics sections. 
Validation needed that URL starts with https:// or http://  
The key that should be sent to the server is grafana_url
The tooltip should say: "The URL of the Grafana dashboard connected to the metrics provider"

Grafana Url should be under metrics like shown here:
<img width="628" alt="Screen Shot 2020-10-09 at 18 03 10" src="https://user-images.githubusercontent.com/11491327/95599416-b92c7e00-0a59-11eb-884c-a9155f13de7a.png">

The last step is add this param to: docs/devguide/docs/configuration.md

**Comment by xevenheaven** [comment]
Hi @enudler, I took a stab at this - PR https://github.com/Zooz/predator/pull/482 created. Is this what is required?

**Comment by enudler** [comment]
Hi @xevenheaven thanks for the PR
Grafana is not a metrics_plugin_name
It shouldn't appear in the dropdown
But it should appear if anything is selected in the dropdown (Prometheus or Influx)
