### ISSUE TITLE
Predator `PUT /config` API expects buckets_sizes to be a string and not an array

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#505]
**Describe the bug**
When configuring prometheus metrics in Predator's config thru the API:
`PUT /v1/config` expects buckets_sizes to be a string and not an array. This is a bug since bucket_sizes **should be** an array

**To Reproduce**
`curl -X PUT \
  http://<predator_url>/v1/config \
  -H 'Content-Type: application/json' \
  -d '{
    "prometheus_metrics": {
    	"push_gateway_url": "http://pushgateway.ops.co:9091",
        "buckets_sizes": [
            0.01,
            0.05,
            0.1,
            0.25,
            0.5,
            0.1,
            0.2,
            0.3,
            0.4,
            0.5,
            1,
            2,
            5,
            10,
            30,
            60,
            120
        ]
    }
}'`

returns a bad request response with body:
```
{
    "message": "Input validation error",
    "validation_errors": [
        "body/prometheus_metrics.buckets_sizes should be string"
    ]
}
```

**Expected behavior**
The response should be 200, and bucket_size should be updated.
1. Update swagger 
2. Add a test

**Version:**
 - Predator: 1.5

**Comment by anusha5695** [comment]
I would pick this

**Comment by enudler** [comment]
hi @anusha5695 
assigned to you

**Comment by anusha5695** [comment]
@enudler : Hi, would you check this please?
