### ISSUE TITLE
Disable deleting tests which are scheduled for runs

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#507]
**Describe the bug**
It's possible to delete the test when it's scheduled to run in the future.
**To Reproduce**
1. Create test
2. Run the test with Cron expression
3. Delete test
4. Test deleted successfully

**Comment by zer0link** [comment]
Hi, can I be asssigned to this issue?

**Comment by enudler** [comment]
Sure @zer0link 
LMK if you need any help

**Comment by zer0link** [comment]
Hi, im having trouble running the test locally by running command 
`npm run set-up-local-env` and `npm test`,
Is there any other dependencies I should install before hand?

**Comment by enudler** [comment]
hi @zer0link 
npm run setup-up-local-env
not 'set'
you will need to use node 12
can you show me the output?

**Comment by zer0link** [comment]
Hi, it is the issue where I use node version 8.x, after upgrading node version and manually installing sqlite3 package I managed to run predator UI

**Comment by syncush** [comment]
@enudler should we add the `sqlite3` installation command in our `setup-local-env` script?

**Comment by enudler** [comment]
@syncush afaik it works fine in node 12 without doing this
I think @zer0link used node 14
maybe it's a good idea
