### ISSUE TITLE
Support for large request body

### ISSUE THREAD

**Issue by maciesse** [Zooz/predator#531]
In our test scenario we need submit a very long request body to a service (the body is ~1Mb since contains and HTML page in base64 format).
Predator version 1.5.4 doesn't support it and raise a "request entity too large" error. This happen when trying to create a new test both with UI or API call too.
Note, this issue not happen using artillery for the same test scenario.

**Comment by enudler** [comment]
Thanks @maciesse 
We will need to adjust the max size in bodyParser

**Comment by enudler** [comment]
hi @maciesse 
now the default limit is 500kb
you can change it env var `BODY_PARSER_LIMIT`
this is in master and will be released in 1.6
would appreciate if you can confirm it's working for you
