### ISSUE TITLE
Stop the runner if test time exceeds the duration given

### ISSUE THREAD

**Issue by NivLipetz** [Zooz/predator#549]
**Describe the bug**
In some configurations the runner keeps sending requests after the test duration is up, in this case the runner should send a `DONE` stat and the test should be marked as `finished`

**To Reproduce**
1. Run 2000 RPS test with 1 parallism on a very fast API server(5ms response rate)
2. No avoided scenarios and therefore the runner will keep sending requests after the time is up

**Expected behavior**
1. Test finish in the expected time duration

**Version:**
 - Predator: 1.6.0
 - Predator-runner: 1.6.0

**Additional context**
Possibility to add this implementation with an environment variable in the predator installation, some users might not want the test to finish and let it keep running

**Comment by syncush** [comment]
I think we should move this issue to the predator-runner

**Comment by enudler** [comment]
fixed in runner project
