### ISSUE TITLE
Is it possible to not use helm ?

### ISSUE THREAD

**Issue by zhchen-zhchen** [Zooz/predator#563]
Hi, I try to use k8s to deploy predator for API load test.

But I am not allowed to use `Helm`. I don't know much about the k8s and this `predator`. May I ask can I use the conventional way to deploy `predator`? 

And I may want to ask if I need one more instance to do the parallel test, what I need is to increase the instance number?

I am not quite sure how data are synchronized between instances and merge into one report.

Thanks

**Comment by ozonep** [comment]
You can do this:
1) Install Helm binary on your local computer, 
2) Download Helm charts
3) Use "helm template" command to generate YAML manifests that are ready fot K8s deployment
https://helm.sh/docs/helm/helm_template/

**Comment by zhchen-zhchen** [comment]
@ozonep 

Thanks for the prompt reply. May I ask how to scale up the number of containers(pods) since I am afraid that only one instance is not enough for my load testing?
I just tried 
```
kubectl scale --replicas=5 deployment my-release-predator
```

but it seems that the test didn't go as expected. Is there anything wrong with my method? or do I need to configure via some environment variables?

**Comment by NivLipetz** [comment]
Hi @zhchen-zhchen , what you are looking for is the `parallelism` parameter when running a test and to set it as 5 for example.

Take a look here for proper configuration of the test run variables:
https://zooz.github.io/predator/myfirsttest.html#running-the-test

**Comment by raymondKelly** [comment]
```
helm install predator zooz/predator --version 1.5.2 --set persistence.enabled=true
helm template zooz/predator > ./template-predator.yaml
```
example commands for those looking for it
