### ISSUE TITLE
Tests all failed but success rates shows 100%

### ISSUE THREAD

**Issue by zhchen-zhchen** [Zooz/predator#564]
report detail page shows all tests failed, but the report list pages show 100% success rates shows
<img width="625" alt="Screen Shot 2021-02-15 at 18 19 42" src="https://user-images.githubusercontent.com/68842344/107927638-9a676680-6fba-11eb-9ba0-c8a9dde7038f.png">
<img width="116" alt="Screen Shot 2021-02-15 at 18 19 51" src="https://user-images.githubusercontent.com/68842344/107927644-9c312a00-6fba-11eb-9d82-3f8b7fd8bb1c.png">

**Comment by NivLipetz** [comment]
this happens because the expectations failed, but all of the requests succeeded. We don't couple the expectations success (assertions on the responses) and the test run success (whether got an OK response from server)

**Comment by zhchen-zhchen** [comment]
I understand. Thanks
