### ISSUE TITLE
Success ratio contains too many decimal number

### ISSUE THREAD

**Issue by zhchen-zhchen** [Zooz/predator#565]
<img width="560" alt="Screen Shot 2021-02-17 at 13 45 24" src="https://user-images.githubusercontent.com/68842344/108157702-b556e980-7126-11eb-816f-6d1a5817373d.png">

https://github.com/Zooz/predator/blob/ee1108ab482ceb0703565ea3086218fb2f55bb10/ui/src/features/redux/selectors/reportsSelector.js#L84

keeping the first two digits after the decimal point will be better?

**Comment by enudler** [comment]
@zhchen-zhchen would be great if you create PR with the change
