### ISSUE TITLE
Unable to upload csv files greater than 10Mb

### ISSUE THREAD

**Issue by Ebaneck** [Zooz/predator#593]
**Describe the bug**
Uploading CSV files greater than 10Mb fails. Please see the screenshot below.

**To Reproduce**
1. In the UI, go to 'Test'
2. Click on 'Create Test'
3. Scroll to 'Add CSV'
4. Drag and drop a CSV file with size e.g 24Mb
5. See error `(Request failed with status code 500)`

**Expected behavior**
I expected that CSV files of any size could be uploaded via the UI

**Screenshots**
 https://ibb.co/2WcMwT8

**Version:**
 - Predator: [1.6.2]
 - Predator-runner [1.6.1]
 - Database [MYSQL]

**Additional context**
While reading the source code [here](https://github.com/Zooz/predator/blob/master/src/app.js#L43), we see that we can customize the file upload size using environmental variables.

Could you please document this [here](https://github.com/Zooz/predator/blob/master/docs/devguide/docs/configuration.md#configuration)

**Comment by enudler** [comment]
Hi @Ebaneck 
thanks for reporting this one
would be great if you can create PR on this

**Comment by Ebaneck** [comment]
Hello @enudler 

Sure, I will find time to have a look.
